apiVersion: apps/v1
kind: Deployment
metadata:
  name: promotion-service
  namespace: prod
  labels:
    app: promotion-service
    environment: prod
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: promotion-service
  template:
    metadata:
      labels:
        app: promotion-service
    spec:
      containers:
        - name: promotion-service
          image: circleguard/promotion-service:latest
          ports:
            - containerPort: 8088
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/circleguard_promotion"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pg-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-credentials
                  key: password
            - name: SPRING_NEO4J_URI
              value: "bolt://neo4j-service:7687"
            - name: SPRING_NEO4J_AUTHENTICATION_USERNAME
              value: "neo4j"
            - name: SPRING_NEO4J_AUTHENTICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: neo4j-secrets
                  key: password
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
            - name: SPRING_DATA_REDIS_HOST
              value: "redis-service"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secrets
                  key: jwt-secret
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
            limits:
              memory: "4Gi"
              cpu: "2000m"

apiVersion: v1
kind: Service
metadata:
  name: promotion-service
  namespace: prod
spec:
  selector:
    app: promotion-service
  ports:
    - port: 8088
      targetPort: 8088

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: promotion-service-pdb
  namespace: prod
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: promotion-service